import { bigint, varchar, text, datetime, date, time, float, int, decimal, mysqlTable, index, tinyint } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

// ============================================
// MOBILE_DATABASE Schema
// Table mapping dari ftlg_master:
//   user -> fr_user
//   club -> fr_door
//   member -> member (sama)
//   list_booking -> list_booking (sama)
//   log_webhook -> webhook_checkin
// ============================================

// fr_user table (sebelumnya: user di ftlg_master)
export const frUser = mysqlTable('fr_user', {
  id: bigint('id', { mode: 'number' }).primaryKey().autoincrement(),
  firstName: varchar('first_name', { length: 255 }),
  lastName: varchar('last_name', { length: 255 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  nik: varchar('nik', { length: 50 }),
  password: varchar('password', { length: 255 }),
  gender: varchar('gender', { length: 10 }),
  dob: date('dob'),
  cityId: bigint('city_id', { mode: 'number' }),
  provinceId: bigint('province_id', { mode: 'number' }),
  clubId: bigint('club_id', { mode: 'number' }),
  address: text('address'),
  trainerLevelId: bigint('trainer_level_id', { mode: 'number' }),
  description: text('description'),
  status: varchar('status', { length: 50 }),
  rejectNote: text('reject_note'),
  activatedBy: bigint('activated_by', { mode: 'number' }),
  activatedDate: datetime('activated_date'),
  joinDate: date('join_date'),
  resignDate: date('resign_date'),
  noteResign: text('note_resign'),
  idBitrix: varchar('id_bitrix', { length: 100 }),
  idGymmaster: varchar('id_gymmaster', { length: 100 }),
  resourceId: bigint('resource_id', { mode: 'number' }),
  idGreatday: varchar('id_greatday', { length: 100 }),
  statusRequest: varchar('status_request', { length: 50 }),
  request: text('request'),
  createdBy: bigint('created_by', { mode: 'number' }),
  updatedAt: datetime('updated_at'),
  noRekening: varchar('no_rekening', { length: 100 }),
  namaRekening: varchar('nama_rekening', { length: 255 }),
  totalHariKerja: int('total_hari_kerja'),
  basicSalary: decimal('basic_salary', { precision: 15, scale: 2 }),
  positionalAllowance: decimal('positional_allowance', { precision: 15, scale: 2 }),
  otherAllowances: decimal('other_allowances', { precision: 15, scale: 2 }),
  isDummy: tinyint('is_dummy'),
  pin: varchar('pin', { length: 10 }),
  roleId: bigint('role_id', { mode: 'number' }),
  isOjt: tinyint('is_ojt'),
  divisionId: bigint('division_id', { mode: 'number' }),
  positionId: bigint('position_id', { mode: 'number' }),
  pemantauan: varchar('pemantauan', { length: 50 }),
  refferalCode: varchar('refferal_code', { length: 50 }),
  userTrainingId: bigint('user_training_id', { mode: 'number' }),
  ptLevel: varchar('pt_level', { length: 50 }),
  certifications: text('certifications'),
  expertise: text('expertise'),
  trainerExperience: text('trainer_experience'),
}, (table) => ({
  emailIdx: index('idx_fr_user_email').on(table.email),
  clubIdIdx: index('idx_fr_user_club_id').on(table.clubId),
}));

// fr_door table (sebelumnya: club di ftlg_master)
export const frDoor = mysqlTable('fr_door', {
  id: bigint('id', { mode: 'number' }).primaryKey().autoincrement(),
  clubOrder: int('club_order'),
  name: varchar('name', { length: 255 }),
  type: varchar('type', { length: 50 }),
  codeAutodebet: varchar('code_autodebet', { length: 100 }),
  namaPerusahaan: varchar('nama_perusahaan', { length: 255 }),
  alias: varchar('alias', { length: 100 }),
  maxClassPilates: int('max_class_pilates'),
  clubOpeningDate: date('club_opening_date'),
  isPresale: tinyint('is_presale'),
  presaleDate: date('presale_date'),
  countryId: bigint('country_id', { mode: 'number' }),
  cityId: bigint('city_id', { mode: 'number' }),
  stateId: bigint('state_id', { mode: 'number' }),
  address: text('address'),
  latitude: varchar('latitude', { length: 50 }),
  longtitude: varchar('longtitude', { length: 50 }),
  maxDistanceMeters: int('max_distance_meters'),
  kordinate: varchar('kordinate', { length: 100 }),
  postalCode: varchar('postal_code', { length: 20 }),
  status: varchar('status', { length: 50 }),
  createdAt: datetime('created_at'),
  updatedBy: bigint('updated_by', { mode: 'number' }),
  updatedAt: datetime('updated_at'),
  linkPayment: text('link_payment'),
  doorid: bigint('doorid', { mode: 'number' }),
  linkGmap: text('link_gmap'),
  facility: text('facility'),
  linkYoutube: text('link_youtube'),
  managerOnDuty: varchar('manager_on_duty', { length: 255 }),
  managerOnDutyWhatsapp: varchar('manager_on_duty_whatsapp', { length: 50 }),
  badges: text('badges'),
  isPadel: tinyint('is_padel'),
  aliasBitrix: varchar('alias_bitrix', { length: 100 }),
  perusahaanId: bigint('perusahaan_id', { mode: 'number' }),
}, (table) => ({
  dooridIdx: index('idx_fr_door_doorid').on(table.doorid),
}));

// member table (nama sama dengan ftlg_master)
export const member = mysqlTable('member', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  firstname: varchar('firstname', { length: 255 }),
  surname: varchar('surname', { length: 255 }),
  preferredname: varchar('preferredname', { length: 255 }),
  fullname: varchar('fullname', { length: 255 }),
  dob: date('dob'),
  gender: varchar('gender', { length: 10 }),
  email: varchar('email', { length: 255 }),
  phonecell: varchar('phonecell', { length: 50 }),
  phonehome: varchar('phonehome', { length: 50 }),
  phonework: varchar('phonework', { length: 50 }),
  phone: varchar('phone', { length: 50 }),
  memberblank: varchar('memberblank', { length: 255 }),
  ddExportFormatid: bigint('dd_export_formatid', { mode: 'number' }),
  canSwitchTo: text('can_switch_to'),
  canSwitchFrom: text('can_switch_from'),
  addresstreet: text('addresstreet'),
  addressareacode: varchar('addressareacode', { length: 20 }),
  addresscountry: varchar('addresscountry', { length: 100 }),
  joindate: date('joindate'),
  tagreal: text('tagreal'),
  companyid: bigint('companyid', { mode: 'number' }),
  state: varchar('state', { length: 50 }),
  goal: text('goal'),
  created: datetime('created'),
  promotionId: bigint('promotion_id', { mode: 'number' }),
  sourcepromotion: varchar('sourcepromotion', { length: 255 }),
  staffid: bigint('staffid', { mode: 'number' }),
  staffname: varchar('staffname', { length: 255 }),
  getReferredbymember: varchar('get_referredbymember', { length: 255 }),
  referredbymemberName: varchar('referredbymember_name', { length: 255 }),
  medicalconditions: text('medicalconditions'),
  doctorname: varchar('doctorname', { length: 255 }),
  doctorphone: varchar('doctorphone', { length: 50 }),
  medicalcentrename: varchar('medicalcentrename', { length: 255 }),
  occupation: varchar('occupation', { length: 255 }),
  organisation: varchar('organisation', { length: 255 }),
  language: varchar('language', { length: 50 }),
  clubname: varchar('clubname', { length: 255 }),
  clubPhone: varchar('club_phone', { length: 50 }),
  clubEmail: varchar('club_email', { length: 255 }),
  clubWebsite: varchar('club_website', { length: 255 }),
  clubReviewUrl: text('club_review_url'),
  emergencyname: varchar('emergencyname', { length: 255 }),
  emergencycell: varchar('emergencycell', { length: 50 }),
  emergencyemail: varchar('emergencyemail', { length: 255 }),
  emergencyrelationship: varchar('emergencyrelationship', { length: 100 }),
  clubAddress: text('club_address'),
  logincode: varchar('logincode', { length: 100 }),
  onlineBookingsEnable: tinyint('online_bookings_enable'),
  onlineBookingsDisabledUntil: datetime('online_bookings_disabled_until'),
  onlineBookingsDisabledSource: varchar('online_bookings_disabled_source', { length: 255 }),
  visitStreak: int('visit_streak'),
  streakThreshold: int('streak_threshold'),
  timezone: varchar('timezone', { length: 100 }),
  enableDirectSearch: tinyint('enable_direct_search'),
  publicLeaderboardOptIn: tinyint('public_leaderboard_opt_in'),
  usableCredit: decimal('usable_credit', { precision: 15, scale: 2 }),
  hasBillingToken: tinyint('has_billing_token'),
  totalvisits: int('totalvisits'),
  totalpts: int('totalpts'),
  totalclasses: int('totalclasses'),
  totalbookings: int('totalbookings'),
  totalmessages: int('totalmessages'),
  totalworkouts: int('totalworkouts'),
  totalmeasurements: int('totalmeasurements'),
  customdropdown1: varchar('customdropdown1', { length: 255 }),
  customdropdown2: varchar('customdropdown2', { length: 255 }),
  customdropdown3: varchar('customdropdown3', { length: 255 }),
  customdropdown4: varchar('customdropdown4', { length: 255 }),
  customdropdown5: varchar('customdropdown5', { length: 255 }),
  customtext1: text('customtext1'),
  customtext2: text('customtext2'),
  customtext3: text('customtext3'),
  customtext4: text('customtext4'),
  customtext5: text('customtext5'),
  customtext6: text('customtext6'),
  customtext7: text('customtext7'),
  customtext8: text('customtext8'),
  status: varchar('status', { length: 50 }),
  memberidphoto: text('memberidphoto'),
  emergencyfirstname: varchar('emergencyfirstname', { length: 255 }),
  emergencysurname: varchar('emergencysurname', { length: 255 }),
}, (table) => ({
  emailIdx: index('idx_member_email').on(table.email),
}));

// list_booking table (nama sama dengan ftlg_master)
export const listBooking = mysqlTable('list_booking', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  day: date('day'),
  starttime: time('starttime'),
  daystarttime: datetime('daystarttime'),
  endtime: time('endtime'),
  resourceName: varchar('resource_name', { length: 155 }),
  clubName: varchar('club_name', { length: 50 }),
  cancelfee: float('cancelfee'),
  cancelbenefitloss: float('cancelbenefitloss'),
  type: varchar('type', { length: 155 }),
  description: text('description'),
  parentid: bigint('parentid', { mode: 'number' }),
  room: bigint('room', { mode: 'number' }),
  equipment: text('equipment'),
  alreadyRepeating: bigint('already_repeating', { mode: 'number' }),
  length: varchar('length', { length: 50 }),
  livestreamurl: int('livestreamurl'),
  result: int('result'),
  isCancelled: int('is_cancelled'),
  memberId: bigint('member_id', { mode: 'number' }),
  showName: text('show_name'),
  myBooking: int('my_booking'),
  faceBookingMember: int('face_booking_member').default(0),
  faceBookingPt: int('face_booking_pt').default(0),
}, (table) => ({
  idIdx: index('idx_list_booking_id').on(table.id),
  memberIdIdx: index('idx_list_booking_member_id').on(table.memberId),
}));

// webhook_checkin table (sebelumnya: log_webhook di ftlg_master)
export const webhookCheckin = mysqlTable('webhook_checkin', {
  id: bigint('id', { mode: 'number' }).primaryKey().autoincrement(),
  doorid: bigint('doorid', { mode: 'number' }),
  doorname: varchar('doorname', { length: 255 }),
  memberid: bigint('memberid', { mode: 'number' }),
  membername: varchar('membername', { length: 255 }),
  cardno: varchar('cardno', { length: 100 }),
  access: varchar('access', { length: 50 }),
  comment: text('comment'),
  membershipid: bigint('membershipid', { mode: 'number' }),
  membershipname: varchar('membershipname', { length: 255 }),
  bookingid: bigint('bookingid', { mode: 'number' }),
  bookingName: varchar('booking_name', { length: 255 }),
  checkinType: varchar('checkin_type', { length: 50 }),
  timestamp: datetime('timestamp'),
  checkinSource: varchar('checkin_source', { length: 100 }),
  hostname: varchar('hostname', { length: 255 }),
}, (table) => ({
  dooridIdx: index('idx_webhook_checkin_doorid').on(table.doorid),
  memberidIdx: index('idx_webhook_checkin_memberid').on(table.memberid),
  bookingidIdx: index('idx_webhook_checkin_bookingid').on(table.bookingid),
}));
